version: '3.8'

services:
  # Production service - optimized build with no hot-reloading
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: mermaid-yang-app:latest
    container_name: mermaid-yang-app
    ports:
      - "3000:3000"
    volumes:
      # Only mount uploads directory for persistent storage
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot-reloading
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: mermaid-yang-app:dev
    container_name: mermaid-yang-app-dev
    ports:
      - "3000:3000"
      - "5173:5173" # Vite dev server
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - /app/frontend/node_modules
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_PORT=5173
    restart: unless-stopped